"""Normalise the post's line wrapping so prose edits stop producing ragged text.

Sections of this post are generated by interpolating computed values into a
template, which leaves lines of wildly different lengths wherever a number was
substituted. Rewrapping by hand then moves line breaks that `verify.py` searches
for, so the two fight each other. Running the wrap from here settles it: prose
is filled to a fixed width, everything that must not be touched is left exactly
as it is, and `verify.py` runs afterwards against the settled text.

Left alone: frontmatter, headings, tables, fenced code, figure shortcodes, list
items and blockquotes. Filling a table would destroy it and filling a list item
would merge the bullets.
"""

from __future__ import annotations

import re
import sys
import textwrap
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
POST = BASE / "post" / "index.md"
WIDTH = 79

__all__ = ["normalise"]

_UNTOUCHED_PREFIXES = ("#", "|", "{{<", "```", "-", "*", ">", "  ")


def _is_prose(block: str) -> bool:
    stripped = block.strip()
    if not stripped or stripped.startswith(_UNTOUCHED_PREFIXES):
        return False
    # A paragraph that turns into a table part way down, which happens when a
    # heading and its table end up in one block.
    return "\n|" not in stripped and "\n```" not in stripped


def _rejoin_split_compounds(block: str) -> str:
    """Repair a compound word already broken across two lines.

    Once "Dickey-Fuller" has been wrapped as "Dickey-" then "Fuller", splitting
    the paragraph on whitespace turns the break into a space and leaves two
    words that no wrap setting can put back together. Turning off hyphen
    breaking stops the damage happening again; this undoes what already
    happened. A hyphen at the end of a line is always a broken compound in this
    post, since nothing here ends a line on a dangling hyphen deliberately.
    """
    return re.sub(r"(\w)-\n(\w)", r"\1-\2", block)


def normalise(text: str) -> str:
    """Return the post with prose paragraphs filled and everything else intact."""
    if text.startswith("---"):
        end = text.index("\n---", 3) + len("\n---")
        head, body = text[:end], text[end:]
    else:
        head, body = "", text

    blocks = body.split("\n\n")
    out = []
    for block in blocks:
        if _is_prose(block):
            # break_on_hyphens off, or "Dickey-Fuller" and "error-correction"
            # split across lines and read as typos.
            mended = _rejoin_split_compounds(block)
            out.append(textwrap.fill(" ".join(mended.split()), width=WIDTH,
                                     break_on_hyphens=False))
        else:
            out.append(block.strip("\n"))
    # Collapse the runs of blank lines that repeated insertions leave behind.
    joined = "\n\n".join(b for b in out if b != "")
    return f"{head}\n\n{joined}\n" if head else f"{joined}\n"


if __name__ == "__main__":
    original = POST.read_text()
    settled = normalise(original)
    if "--check" in sys.argv:
        if settled != original:
            print("post/index.md is not normalised; run python analysis/format_post.py")
            raise SystemExit(1)
        print("post/index.md wrapping is settled")
        raise SystemExit(0)
    POST.write_text(settled)
    changed = sum(a != b for a, b in
                  zip(original.splitlines(), settled.splitlines()))
    print(f"normalised post/index.md, {changed} lines rewrapped, "
          f"{len(original.splitlines())} to {len(settled.splitlines())}")
